export const headerColors = [
  'bg-blue-700 bg-dotted-pattern',
  'bg-gray-700 bg-grid-pattern',
  'bg-green-800 bg-dotted-pattern',
  'bg-purple-800 bg-diagonal-lines',
  'bg-yellow-700 bg-dotted-pattern',
  'bg-indigo-700 bg-grid-pattern',
  'bg-white/7 bg-dotted-pattern',
  'bg-red-700 bg-diagonal-lines',
  'bg-teal-700 bg-dotted-pattern',
  'bg-pink-600 bg-grid-lines',
];

export const columnsData = [
  {
    id: 1,
    title: 'Todo',
    general: 'todo',
    color: 'bg-blue-700 light:text-white',
    border: 'border-l-[2px] border-l-blue-600',
    shadow: 'inset-shadow-sm inset-shadow-blue-600',
  },
  {
    id: 2,
    title: 'In_progress',
    general: 'in progress',
    color: 'bg-purple-700 light:text-white',
    border: 'border-l-[2px] border-l-purple-600',
    shadow: 'inset-shadow-sm inset-shadow-purple-600',
  },
  {
    id: 3,
    title: 'Ready_for_review',
    general: 'ready for review',
    color: 'bg-yellow-700 light:text-white',
    border: 'border-l-[2px] border-l-yellow-600',
    shadow: 'inset-shadow-sm inset-shadow-yellow-600',
  },
  {
    id: 4,
    title: 'In_review',
    general: 'in review',
    color: 'bg-teal-700 light:text-white',
    border: 'border-l-[2px] border-l-teal-600',
    shadow: 'inset-shadow-sm inset-shadow-teal-600',
  },
  {
    id: 5,
    title: 'Done',
    general: 'done',
    color: 'bg-green-700 light:text-white',
    border: 'border-l-green-600',
    shadow: 'inset-shadow-sm inset-shadow-green-600',
  },
];
